name: Java CI with Maven

on: pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: jar
          path: /home/runner/work/oel-remake-components/oel-remake-components/target/oel-remake-components.jar
